"""
ThinkVault AI — Seed Script
Creates a demo user and sample documents.

Usage:
  cd backend
  DATABASE_URL=... GEMINI_API_KEY=... DEEPSEEK_API_KEY=... .venv/bin/python seed.py
"""

import asyncio
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker
from app.core.config import settings
from app.models.user import User
from app.models.document import Document
from app.core.security import hash_password
import uuid

SAMPLE_DOCS = [
    {
        "title": "Introduction to Machine Learning",
        "source_type": "text",
        "content": """Machine learning is a subset of artificial intelligence that enables systems to learn 
        from data without being explicitly programmed. The key paradigms are supervised learning, 
        unsupervised learning, and reinforcement learning. Supervised learning uses labeled training data 
        to learn a mapping from inputs to outputs. Common algorithms include linear regression, decision trees, 
        random forests, support vector machines, and neural networks. Unsupervised learning discovers patterns 
        in unlabeled data through clustering (k-means, DBSCAN) and dimensionality reduction (PCA, t-SNE). 
        Deep learning uses multi-layer neural networks to learn hierarchical representations, achieving 
        state-of-the-art results in computer vision, NLP, and speech recognition.""",
    },
    {
        "title": "Vector Databases and Semantic Search",
        "source_type": "text",
        "content": """Vector databases store high-dimensional embeddings and enable semantic similarity search. 
        Unlike traditional keyword search, semantic search understands meaning and context. Embeddings are 
        dense vector representations of text generated by neural language models like BERT, GPT, or Gemini. 
        pgvector is a PostgreSQL extension that adds vector similarity search capabilities. It supports 
        L2 distance, inner product, and cosine similarity operators. The ivfflat index (Inverted File with 
        Flat quantization) enables approximate nearest neighbor search at scale, making it practical for 
        large datasets. Retrieval Augmented Generation (RAG) combines vector search with large language 
        models to answer questions grounded in specific document collections.""",
    },
]


async def seed():
    engine = create_async_engine(settings.DATABASE_URL, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with async_session() as db:
        # Create demo user
        demo_user = User(
            id=uuid.uuid4(),
            email="demo@thinkvault.ai",
            hashed_password=hash_password("demo1234"),
            full_name="Demo User",
        )
        db.add(demo_user)
        await db.commit()
        await db.refresh(demo_user)
        print(f"✅ Created demo user: {demo_user.email}")

        # Create sample documents (will be processed by API on real usage)
        for doc_data in SAMPLE_DOCS:
            doc = Document(
                user_id=demo_user.id,
                title=doc_data["title"],
                source_type=doc_data["source_type"],
                raw_text=doc_data["content"],
                status="pending",
            )
            db.add(doc)

        await db.commit()
        print(f"✅ Created {len(SAMPLE_DOCS)} sample documents")
        print("\n🎉 Seed complete! Login with: demo@thinkvault.ai / demo1234")

    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(seed())
